# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5419fc25c7b380d7c872a17ffdccd9cebf8e18d0761d4f38f6a22a1f7ec1df35e22fae215088b093aabea48d0f0a32bc470b16eaf33110e5583f2e247222f97e

test:
  secret_key_base: cc1a32b358f7d0a041dbcda1f53bb00646e4b0aefc91f35f5d26629cb3f6f2958df399a260cadd1cf93f9e144933bbe3c8d9c2d0ea9b1ec00dd2c40f8efc516a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
